for Line in ` ls -Shr  | tail -140 `;do
    ./Thicken2 $Line
done




12.obj  
18.obj  
20.obj  
4.obj  
5.obj  
BendTube.obj  
BracketInches.obj  
CoverSlipCleaningHolder2b.obj  
Hub.obj  
LowerControlArm.obj  
anti_backlash_nut.obj  
asm007.obj  
bamboo_pen.obj  
bearing_plate.obj  
beveled_shoulder_1.obj  
beveled_shoulder_2.obj  
blade.obj  
bladefem.obj  
bolt.obj  
bone.obj  
bone1.obj  
bozbezbozzel50K.obj  
buddha.obj  
bunny.obj  
casting.obj  
casting2.obj  
cow2.obj  
cube_carved.obj  
cube_minus_sphere.obj  
cup-tri.obj  
deckel.obj  
delta_arm2_remesh.obj  
des6.obj  
des7.obj  
eros100K.obj  
fandisk.obj  
fertility.obj  
greek_sculpture.obj  
gyroidpuzzle.obj  
halved_oblique_scarf_2.obj  
halved_oblique_scarf_3.obj  
hinge.obj  
impeller.obj  
inlay_dovetail_3.obj  
israel.obj  
joint.obj  
lego.obj  
lion.obj  
lock_Lp.obj  
magalie_hand100K.obj  
mech10.obj  
mech_piece.obj  
mechanical02.obj  
mechanical03.obj  
mechanical04.obj  
mid2Fem.obj  
motor_tail.obj  
mount.obj  
nasty_cheese.obj  
nugear.obj  
octa_flower_Lp.obj  
part2.obj  
part20k.obj  
pinion.obj  
plate_1.obj  
plate_Lp.obj  
switchmec_Lp.obj  
teapot.obj  
toothbrush_holder.obj  
ujoint.obj  
wedge.obj  